// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkjfasbypydktiygviye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpramZhc2J5cHlka3RpeWd2aXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDY1ODIsImV4cCI6MjA3Mzg4MjU4Mn0.8VQgA7OCwcv4sPccRu71rUSQPrp2ir4O8jvLwutNzqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});